import "./globals.css";

export const metadata = {
  title: "Edu-Bridge",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`} suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}
